#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniquePassword.AndroidApplication.Resource", IsApplication=true)]

namespace UniquePassword.AndroidApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int textColorPrimary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int windowBackground = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int ButtonCopy = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int LabelDomainDesc = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int LabelDomainText = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int LabelHashedDesc = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int LabelHashedText = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int LabelLengthText = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int LabelMasterDesc = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int LabelMasterText = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int LabelSpecialsText = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int LayoutHashed = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int ListRecent = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int PagerTabStrip = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int TextDomain = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int TextHashed = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int TextLength = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int TextMaster = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int TextSpecials = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int ViewPager = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Data = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Recent = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int UniquePasswordTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
